### ISSUE TITLE
Загрузка/сохранение файла #16

### ISSUE THREAD

**Issue by Midova** [Midova/mcounter#16]
В приложении MoneyCounter создать каталог Services.
В каталоге Services создать интерфейсs: IOpenProjectFileService и  ISaveProjectFileService.
В каталоге Services создать классы:  OpenProjectFileService и SaveProjectFileService, наследуемые от интерфейсов  IOpenProjectFileService и  ISaveProjectFileService.

**Comment by vladidemidov** [comment]
Для проверки работы данных сервисов надо так жде дополнить имеющиеся юнит тесты.
Для этого нужно классы тестов для каждого сервиса. Сами методы тестов должны покрывать различные случаи, к примеру пустые строки к сохранению и тому подобное. Тесты нужно создать в уже имеющимся проекте. Классы тестов надо размещать на одном уровне с уже имеющимися.
